apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

namePrefix: prod-
nameSuffix: -v1

commonLabels:
  app: webapp-1

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
