apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Staging project for gitops-argocd.
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: production
#   namespace: argocd
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   description: Production project for gitops-argocd.
#   sourceRepos:
#     - "*"
#   destinations:
#     - namespace: "*"
#       server: https://kubernetes.default.svc
#   clusterResourceWhitelist:
#     - group: "*"
#       kind: "*"
#   namespaceResourceWhitelist:
#     - group: "*"
#       kind: "*"
