---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-app-one
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-argocd
  source:
    repoURL: https://github.com/RustyTake-Off/gitops-argocd.git
    targetRevision: main
    path: deployments/environments/staging/app_one
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 3s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-app-two
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-argocd
  source:
    repoURL: https://github.com/RustyTake-Off/gitops-argocd.git
    targetRevision: main
    path: deployments/environments/production/app_two
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 3s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
