---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: gitops-argocd
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.6.0
    chart: ingress-nginx
    helm:
      version: v3
      passCredentials: false
      parameters:
        - name: "image.tag"
          value: v1.7.0
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 3s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
