apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base

commonLabels:
  app: webapp

commonAnnotations:
  project: gitops-argocd

namespace: staging

namePrefix: staging-
nameSuffix: -v1
